### ISSUE TITLE
TimeZone info in Mongo is inaccurate

### ISSUE THREAD

**Issue by mscappini** [aisthesis/optbot#8]
It looks like the timezone information being inserted with the quote records is wrong. Somehow, somewhere, between the quotes service and the database, the timezone is not being set or is being lost. Here is a document from Mongo (the newest data I have):

{
    "_id": ObjectId('55243b80ed1ffd08235c3e1e'),
    "Open_Int": 3513,
    "Last": 0.1,
    "Vol": 5,
    "Bid": 0,
    "Opt_Type": "call",
    "Expiry": ISODate('2016-01-15T04:56:00.000Z'),
    "Ask": 0.1,
    "Quote_Time": ISODate('2015-04-07T20:00:00.986Z'),
    "Underlying": "SCTY",
    "Strike": 170,
    "Opt_Symbol": "SCTY160115C00170000"
}

Notice the Z at the end of the Expiry and Quote_Time. I was actually mistaken about the meaning of this character. It's actually representative of [UTC](http://en.wikipedia.org/wiki/Coordinated_Universal_Time#Time_zones). This is better than _no_ timezone, but I believe we'd want to store the timezone based on where the exchange is? Or all as UTC. Whatever works best.

Either way, it doesn't look like the UTC is being inserted properly.

**Comment by aisthesis** [comment]
That's consistent with what the instance in google cloud is showing:

```
> use options
switched to db options
> db.quotes.findOne({'Quote_Time': { $gte: new Date('04/09/2015')}})
{
    "_id" : ObjectId("5526de19ed1ffd08235c5bca"),
    "Open_Int" : 10,
    "Last" : 0.08,
    "Vol" : 10,
    "Bid" : 0,
    "Opt_Type" : "put",
    "Expiry" : ISODate("2015-06-19T04:56:00Z"),
    "Ask" : 0.1,
    "Quote_Time" : ISODate("2015-04-09T20:00:00.841Z"),
    "Underlying" : "SPWR",
    "Strike" : 12,
    "Opt_Symbol" : "SPWR150619P00012000"
}
> 
```

**Comment by mscappini** [comment]
I guess it's a question of: is this the desired result?

**Comment by aisthesis** [comment]
According to [this](http://stackoverflow.com/questions/23987332/joda-datetime-isodatetimeformat-pattern), the 'Z' represents UTC, in which case the information is accurate.

**Comment by mscappini** [comment]
I can't remember based on our conversation, but did we want to store that as UTC or the timezone of the exchange?

**Comment by aisthesis** [comment]
This is what was happening before setting the timezone in our code (i.e., where python has `tzinfo=None`):

```
> db.quotes.findOne({'Quote_Time': {$lt: new Date('04/01/2015')}})
{
    "_id" : ObjectId("550e5581ed1ffd3bc158fe67"),
    "Open_Int" : 10,
    "Last" : 0.08,
    "Vol" : 10,
    "Bid" : 0,
    "Opt_Type" : "put",
    "Expiry" : ISODate("2015-06-19T00:00:00Z"),
    "Ask" : 0.22,
    "Quote_Time" : ISODate("2015-03-22T16:00:00Z"),
    "Underlying" : "SPWR",
    "Strike" : 12,
    "Opt_Symbol" : "SPWR150619P00012000"
}
>
```

**Comment by aisthesis** [comment]
I thought the conclusion today was that it doesn't matter a lot, as long as there _is_ a timezone and the entry is accurate. If pymongo is accurately converting to UTC for us, I don't have a problem with that. As discussed, it might be desirable both for data insertion and data retrieval to convert to Eastern for U.S. exchanges so that we don't have to deal with difficult logic for DST.

**Comment by mscappini** [comment]
Works for me.
